### ISSUE TITLE
storybook jumps into the node_modules to include other stories

### ISSUE THREAD

**Issue by pankajpatel** [holidaypirates/ascesis-storybook#15]
I have two components and and one of them is devDependency for another named [`inspector-component`](https://github.com/pankajpatel/inspector-component) and [`dates`](https://github.com/pankajpatel/dates) respectively and both of them have some stories.

When I run stories in `dates`, storybook grabs stories from `inspector-component` as well.

`dates` has following config:
```js
module.exports = {
  storiesMask: '**/stories/*'
}
```

**Comment by nogizhopaboroda** [comment]
try storiesMask value `'stories/*'` or `'../stories/*'` or `'/stories/**'`. this should solve your issue now. would 'excludeDir' or similar option in config help?

**Comment by pankajpatel** [comment]
`'**/dates/stories/*'` solved issue.
Maybe because we match the above mask to full path. 

Though storybook should not look into the `node_modules`

**Comment by nogizhopaboroda** [comment]
resolved https://github.com/holidaypirates/ascesis-storybook/pull/16
