### ISSUE TITLE
Event Data along with the Events

### ISSUE THREAD

**Issue by pankajpatel** [holidaypirates/ascesis-storybook#30]
It will be great to show the `eventData` along with the event being fired, this will reduce the need to open the debugger.

**Comment by nogizhopaboroda** [comment]
the question is how to show it. json pretty-print?

**Comment by pankajpatel** [comment]
We can start with JSON pretty-print, though `inspector-component` will be good usage as we will have plain object now.

Though we can specify which keys from the EventData should be shown.
